# Generated by Django 4.1.3 on 2023-08-08 13:19

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_en', models.CharField(blank=True, max_length=32, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 't_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InappropriatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(280)], verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Inappropriate Post',
                'verbose_name_plural': 'Inappropriate Posts',
                'db_table': 't_inappropriate_post',
            },
        ),
        migrations.CreateModel(
            name='OrderedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateField(null=True, verbose_name='Bitiş Tarihi')),
            ],
            options={
                'verbose_name': 'Ordered Package',
                'verbose_name_plural': 'Ordered Packages',
                'db_table': 't_ordered_package',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('amount', models.PositiveSmallIntegerField(default=1, verbose_name='Toplam Adet')),
                ('gift', models.PositiveSmallIntegerField(default=1, verbose_name='Hediye')),
                ('days_delta', models.PositiveSmallIntegerField(default=365, verbose_name='Kalan Günler')),
                ('css_class', models.CharField(blank=True, max_length=140, null=True)),
                ('price_per', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Birim Fiyat')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='İndirim')),
                ('currency_symbol', models.CharField(default='₺', max_length=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 't_package',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('body', ckeditor.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(81920)])),
                ('slug', models.SlugField(max_length=250, unique_for_date='created_date')),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 't_post',
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostCreateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rule', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Post Create Rule',
                'verbose_name_plural': 'Post Create Rules',
                'db_table': 't_post_create_rule',
            },
        ),
        migrations.CreateModel(
            name='PostPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('used', models.SmallIntegerField(default=0, verbose_name='Used')),
                ('ordered_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.orderedpackage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'verbose_name': 'Post Package',
                'verbose_name_plural': 'Post Packages',
                'db_table': 't_post_package',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/posts/', verbose_name='Resim')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
                'db_table': 't_post_image',
            },
        ),
    ]
