# Generated by Django 4.1.3 on 2023-08-08 13:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('description', ckeditor.fields.RichTextField()),
                ('lesson_count', models.PositiveSmallIntegerField(default=0)),
                ('duration', models.DurationField()),
                ('intro_url', models.URLField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='course-slug', max_length=250, unique=True)),
                ('custom_css_style', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_course',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='target_attachments')),
                ('title', models.CharField(max_length=140)),
                ('description', ckeditor.fields.RichTextField()),
                ('duration', models.DurationField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_lecture',
            },
        ),
        migrations.CreateModel(
            name='UserLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lecture')),
            ],
            options={
                'db_table': 't_user_lecture',
            },
        ),
    ]
