# Generated by Django 4.1.3 on 2023-08-08 13:19

import apps.developers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 't_skill',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('job_title', models.CharField(max_length=32)),
                ('linkedin_pp_url', models.URLField(blank=True, max_length=512, null=True)),
                ('linkedin', models.URLField(default=apps.developers.models.get_site, max_length=64)),
                ('twitter', models.URLField(default=apps.developers.models.get_site, max_length=32)),
                ('github', models.URLField(default=apps.developers.models.get_site, max_length=32)),
                ('website', models.URLField(default=apps.developers.models.get_site, max_length=32)),
                ('skills', models.ManyToManyField(to='developers.skill')),
            ],
            options={
                'db_table': 't_developer',
            },
        ),
    ]
